/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Check one document and return typed, explained suggestions.
         */
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze File
         * @description Check an uploaded file: .docx, .tex, an Overleaf .zip, .md/.qmd/.Rmd
         *     or .txt. The body is the raw file; it is read in memory and discarded.
         */
        post: operations["analyzeFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze-word": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Word
         * @description Check a Word document sent as its paragraphs (the Word add-in, S3).
         *     Each suggestion says which paragraph it is in and how to find it there,
         *     because Word has no character offsets.
         */
        post: operations["analyzeWord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Per-tier status. A degraded tier is reported, never hidden.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/learn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Learn Index
         * @description Every Learn card, grouped in reading order (S4). No document text.
         */
        get: operations["listLearn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/learn/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Learn Card
         * @description One Learn card, by the `learn_ref` a suggestion carries.
         */
        get: operations["getLearnCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rules
         * @description The rule registry with why/source — powers Explain and settings UIs.
         */
        get: operations["listRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeFileResponse */
        AnalyzeFileResponse: {
            /** @description Present when `options.checklist` was set and resolved to a checklist. */
            checklist?: components["schemas"]["ChecklistReport"] | null;
            /**
             * Counts
             * @description Shown suggestions per category.
             */
            counts: {
                [key: string]: number;
            };
            document: components["schemas"]["SourceInfo"];
            /** Elapsed Ms */
            elapsed_ms: number;
            engine: components["schemas"]["EngineInfo"];
            /**
             * Health
             * @description Every surface must show a degraded tier (CLAUDE.md: no silent tiers).
             */
            health: components["schemas"]["TierHealth"][];
            /**
             * Hidden By Mode
             * @description Document-level suggestions Draft mode held back (0 in Revise).
             * @default 0
             */
            hidden_by_mode: number;
            /** Hidden Preferences */
            hidden_preferences: number;
            metrics?: components["schemas"]["Metrics"] | null;
            /**
             * @description The mode this check ran in.
             * @default revise
             */
            mode: components["schemas"]["Mode"];
            /** @description Present when `options.narrative` was true. */
            narrative?: components["schemas"]["NarrativeMap"] | null;
            /** @description The article-type profile this check ran under. */
            profile?: components["schemas"]["ProfileInfo"];
            /** @description Present when `options.review` was true. */
            review?: components["schemas"]["ReviewReport"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Sections Detected */
            sections_detected: string[];
            /**
             * Signed In
             * @description True when a valid account token came with the request and its settings were looked up.
             * @default false
             */
            signed_in: boolean;
            /**
             * Suggested Checklist
             * @description The reporting checklist the text's own words point to, if any (always computed; offer it).
             */
            suggested_checklist?: string | null;
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
            /**
             * Warnings
             * @description What was skipped or approximated while reading the text, e.g. LaTeX that could not be parsed and was read with a simpler method. May quote the caller's own text; never logged.
             */
            warnings?: string[];
        };
        /** AnalyzeOptions */
        AnalyzeOptions: {
            /** @description Check the text against a reporting checklist (`checklist` in the response): a guideline's id, or `auto` for the one the text's words point to. */
            checklist?: components["schemas"]["ChecklistChoice"] | null;
            /**
             * Disabled Rules
             * @description Rule ids to mute for this request, e.g. ["G101"]. For a signed-in caller these are added to the rules muted in their account settings.
             */
            disabled_rules?: string[];
            /** @description The article type to check as. Omitted: the caller's saved setting, else auto. */
            document_type?: components["schemas"]["DocumentType"] | null;
            /** @description Draft or Revise for this request. Omitted: the caller's saved setting, else revise. */
            mode?: components["schemas"]["Mode"] | null;
            /**
             * Narrative
             * @description Also build the narrative map (`narrative` in the response) from the same analysis.
             * @default false
             */
            narrative: boolean;
            /**
             * Review
             * @description Also build the critical reader's brief (`review` in the response) from the same analysis.
             * @default false
             */
            review: boolean;
            /**
             * Show Preferences
             * @description Include Preference-type suggestions (hidden by default).
             * @default false
             */
            show_preferences: boolean;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Content
             * @description The document text. Held in memory for this request only; never stored or logged.
             */
            content: string;
            /**
             * @description How to read `content`.
             * @default plain
             */
            format: components["schemas"]["Format"];
            options?: components["schemas"]["AnalyzeOptions"];
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** @description Present when `options.checklist` was set and resolved to a checklist. */
            checklist?: components["schemas"]["ChecklistReport"] | null;
            /**
             * Counts
             * @description Shown suggestions per category.
             */
            counts: {
                [key: string]: number;
            };
            /** Elapsed Ms */
            elapsed_ms: number;
            engine: components["schemas"]["EngineInfo"];
            /**
             * Health
             * @description Every surface must show a degraded tier (CLAUDE.md: no silent tiers).
             */
            health: components["schemas"]["TierHealth"][];
            /**
             * Hidden By Mode
             * @description Document-level suggestions Draft mode held back (0 in Revise).
             * @default 0
             */
            hidden_by_mode: number;
            /** Hidden Preferences */
            hidden_preferences: number;
            metrics?: components["schemas"]["Metrics"] | null;
            /**
             * @description The mode this check ran in.
             * @default revise
             */
            mode: components["schemas"]["Mode"];
            /** @description Present when `options.narrative` was true. */
            narrative?: components["schemas"]["NarrativeMap"] | null;
            /** @description The article-type profile this check ran under. */
            profile?: components["schemas"]["ProfileInfo"];
            /** @description Present when `options.review` was true. */
            review?: components["schemas"]["ReviewReport"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Sections Detected */
            sections_detected: string[];
            /**
             * Signed In
             * @description True when a valid account token came with the request and its settings were looked up.
             * @default false
             */
            signed_in: boolean;
            /**
             * Suggested Checklist
             * @description The reporting checklist the text's own words point to, if any (always computed; offer it).
             */
            suggested_checklist?: string | null;
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
            /**
             * Warnings
             * @description What was skipped or approximated while reading the text, e.g. LaTeX that could not be parsed and was read with a simpler method. May quote the caller's own text; never logged.
             */
            warnings?: string[];
        };
        /** AnalyzeWordRequest */
        AnalyzeWordRequest: {
            options?: components["schemas"]["AnalyzeOptions"];
            /**
             * Paragraphs
             * @description The document's paragraphs in order. Held in memory for this request only; never stored or logged.
             */
            paragraphs: components["schemas"]["WordParagraph"][];
        };
        /** AnalyzeWordResponse */
        AnalyzeWordResponse: {
            /** @description Present when `options.checklist` was set and resolved to a checklist. */
            checklist?: components["schemas"]["ChecklistReport"] | null;
            /**
             * Counts
             * @description Shown suggestions per category.
             */
            counts: {
                [key: string]: number;
            };
            coverage: components["schemas"]["Coverage"];
            /** Elapsed Ms */
            elapsed_ms: number;
            engine: components["schemas"]["EngineInfo"];
            /**
             * Health
             * @description Every surface must show a degraded tier (CLAUDE.md: no silent tiers).
             */
            health: components["schemas"]["TierHealth"][];
            /**
             * Hidden By Mode
             * @description Document-level suggestions Draft mode held back (0 in Revise).
             * @default 0
             */
            hidden_by_mode: number;
            /** Hidden Preferences */
            hidden_preferences: number;
            metrics?: components["schemas"]["Metrics"] | null;
            /**
             * @description The mode this check ran in.
             * @default revise
             */
            mode: components["schemas"]["Mode"];
            /** @description Present when `options.narrative` was true. */
            narrative?: components["schemas"]["NarrativeMap"] | null;
            /** @description The article-type profile this check ran under. */
            profile?: components["schemas"]["ProfileInfo"];
            /** @description Present when `options.review` was true. */
            review?: components["schemas"]["ReviewReport"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Sections Detected */
            sections_detected: string[];
            /**
             * Signed In
             * @description True when a valid account token came with the request and its settings were looked up.
             * @default false
             */
            signed_in: boolean;
            /**
             * Suggested Checklist
             * @description The reporting checklist the text's own words point to, if any (always computed; offer it).
             */
            suggested_checklist?: string | null;
            /** Suggestions */
            suggestions: components["schemas"]["WordSuggestion"][];
            /**
             * Warnings
             * @description What was skipped or approximated while reading the text, e.g. LaTeX that could not be parsed and was read with a simpler method. May quote the caller's own text; never logged.
             */
            warnings?: string[];
        };
        /**
         * Category
         * @description The four-type taxonomy (CLAUDE.md #3). Conventions are never errors;
         *     preferences are hidden unless asked for.
         * @enum {string}
         */
        Category: "correction" | "improvement" | "convention" | "preference";
        /**
         * ChecklistChoice
         * @description Reporting checklists of the discipline packs (S4, P3).
         * @enum {string}
         */
        ChecklistChoice: "auto" | "strobe" | "consort" | "prisma" | "epiforge";
        /** ChecklistChoiceInfo */
        ChecklistChoiceInfo: {
            /** Design */
            design: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Pack */
            pack: string;
        };
        /** ChecklistItem */
        ChecklistItem: {
            /**
             * Evidence
             * @description The sentence that reports it (never logged).
             */
            evidence?: string | null;
            /** Id */
            id: string;
            /** Plain */
            plain: string;
            /** Question */
            question: string;
            /**
             * Sections
             * @description Where readers look for it.
             */
            sections?: string[];
            /**
             * Status
             * @description needs_check is a prompt, never a verdict: the item may be in a table, a figure or the supplement, or not apply.
             * @enum {string}
             */
            status: "reported" | "needs_check";
            /** Topic */
            topic: string;
        };
        /**
         * ChecklistReport
         * @description A reporting checklist checked against the text: reporting only,
         *     never the science.
         */
        ChecklistReport: {
            /** Design */
            design: string;
            /** Id */
            id: string;
            /** Items */
            items: components["schemas"]["ChecklistItem"][];
            /** Label */
            label: string;
            /** Note */
            note: string;
            /** Reported */
            reported: number;
            /** Source */
            source: string;
            /**
             * Suggested
             * @description True when the text's own words point to this checklist.
             */
            suggested: boolean;
            /** Total */
            total: number;
        };
        /**
         * Coverage
         * @description What was and was not read, stated plainly.
         */
        Coverage: {
            /**
             * Not Checked
             * @description Parts of a Word document Office JS does not hand over, e.g. footnotes.
             */
            not_checked: string[];
            /** Paragraphs */
            paragraphs: number;
            /** Table Paragraphs */
            table_paragraphs: number;
        };
        /**
         * DocumentType
         * @description Article-type profile (S4). `auto` guesses from the headings and is
         *     otherwise `general`; the others switch off the checks that do not
         *     apply to that kind of document and say what section unheaded prose is
         *     in (a commentary is argued like a Discussion).
         * @enum {string}
         */
        DocumentType: "auto" | "general" | "manuscript" | "thesis-chapter" | "abstract" | "commentary" | "policy-brief" | "grant" | "response-to-reviewers";
        /** EngineInfo */
        EngineInfo: {
            /** Core Version */
            core_version: string;
            /** Rules Loaded */
            rules_loaded: number;
            /** Service Version */
            service_version: string;
        };
        /**
         * ErrorBody
         * @description Every non-2xx response. `code` is stable and machine-readable;
         *     `message` is for people and never contains document text.
         */
        ErrorBody: {
            /**
             * Code
             * @description One of: invalid_request, malformed_json, malformed_request, payload_too_large, unsupported_media_type, unsupported_file, unreadable_file, unauthorized, sign_in_required, auth_unavailable, rate_limited, not_found, method_not_allowed, internal, or http_error for any other HTTP status
             */
            code: string;
            /** Message */
            message: string;
            /**
             * Request Id
             * @description Quote this when reporting a problem.
             */
            request_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * FixSafety
         * @enum {string}
         */
        FixSafety: "safe" | "review";
        /**
         * Format
         * @description Formats of pasted `content`. Files (.docx, .tex, Overleaf .zip, …) go
         *     to /v1/analyze-file instead; `word_paragraphs` arrives with the hosted
         *     add-in (S3).
         * @enum {string}
         */
        Format: "plain" | "markdown" | "latex";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            engine: components["schemas"]["EngineInfo"];
            /**
             * Status
             * @description degraded when any tier the service is configured to run is not ok.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Tiers */
            tiers: components["schemas"]["TierHealth"][];
        };
        /**
         * HedgingPoint
         * @description Hedges and boosters per 100 words in one section: a trajectory, not a score.
         */
        HedgingPoint: {
            /** Boosters Per 100W */
            boosters_per_100w: number;
            /** Hedges Per 100W */
            hedges_per_100w: number;
            /** Label */
            label: string;
            /**
             * Reading
             * @description flat | hedged | assertive | balanced | heavily hedged
             */
            reading: string;
            /** Section */
            section: string;
            /** Words */
            words: number;
        };
        /**
         * LearnCard
         * @description A short lesson behind a suggestion (S4): plain words, one invented
         *     before-and-after, a habit to check your own draft, the sources.
         */
        LearnCard: {
            /** After */
            after: string;
            /** Before */
            before: string;
            /** Group */
            group: string;
            /** Habit */
            habit: string;
            /** Id */
            id: string;
            /** Lesson */
            lesson: string;
            /** Moves */
            moves?: string[];
            /** Rules */
            rules?: string[];
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** LearnResponse */
        LearnResponse: {
            /** Cards */
            cards: components["schemas"]["LearnCard"][];
        };
        /**
         * Metrics
         * @description Read-outs, never a score (metrics.py).
         */
        Metrics: {
            /** Boosters Per 100W */
            boosters_per_100w: number;
            /** Hedge Booster Balance */
            hedge_booster_balance?: string | null;
            /** Hedges Per 100W */
            hedges_per_100w: number;
            /** Long Sentences */
            long_sentences: number;
            /** Mean Sentence Len */
            mean_sentence_len: number;
            /** Nominalizations Per 100W */
            nominalizations_per_100w: number;
            /**
             * Passive Share By Section
             * @description Share of clauses in the passive voice per section, as a fraction 0-1.
             */
            passive_share_by_section?: {
                [key: string]: number;
            };
            /** Self Mention Per 100W */
            self_mention_per_100w: number;
            /** Sentences */
            sentences: number;
            /** Words */
            words: number;
        };
        /**
         * MissingLink
         * @description A link in the argument's chain (claim, grounds, warrant) that could
         *     not be found near a claim, in one section.
         */
        MissingLink: {
            /** Code */
            code: string;
            /**
             * Evidence
             * @description The sentences concerned (never logged).
             */
            evidence?: string[];
            /** Label */
            label: string;
            /** Learn Ref */
            learn_ref?: string | null;
            /** Message */
            message: string;
            /** Section */
            section: string;
            /** Source */
            source: string;
        };
        /**
         * Mode
         * @description Draft / Revise (P1). Draft shows sentence-level checks only; Revise
         *     shows everything. A writing stage, not a quality dial.
         * @enum {string}
         */
        Mode: "draft" | "revise";
        /**
         * MoveStatus
         * @enum {string}
         */
        MoveStatus: "present" | "missing" | "out_of_order";
        /**
         * NarrativeMap
         * @description Per section, which moves are present, missing or out of order; the
         *     argument's missing links; the hedging trajectory. Same analysis as the
         *     suggestions.
         */
        NarrativeMap: {
            /** Hedging */
            hedging?: components["schemas"]["HedgingPoint"][];
            /** Missing Links */
            missing_links?: components["schemas"]["MissingLink"][];
            /**
             * Note
             * @description One line summing up the map, or why there is none.
             */
            note: string;
            profile?: components["schemas"]["DocumentType"] | null;
            /** Sections */
            sections: components["schemas"]["NarrativeSection"][];
            /** Source */
            source: string;
            /**
             * Unmapped
             * @description Sections found that have no expected moves (topical headings).
             */
            unmapped?: string[];
        };
        /**
         * NarrativeMove
         * @description One expected move of a section, as an authored question.
         */
        NarrativeMove: {
            /**
             * Evidence
             * @description The sentence the move rests on, when present (never logged).
             */
            evidence?: string | null;
            /**
             * Frame
             * @description A fill-in frame in Researchly's own wording: curated text, never generated.
             */
            frame: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Learn Ref
             * @description The Learn card for this move (GET /v1/learn/{id}).
             */
            learn_ref?: string | null;
            /**
             * Note
             * @description For an out-of-order move: what it appears before or after.
             * @default
             */
            note: string;
            /**
             * Plain
             * @description The lesson, in everyday words.
             */
            plain: string;
            /** Question */
            question: string;
            /** Source */
            source: string;
            status: components["schemas"]["MoveStatus"];
        };
        /** NarrativeSection */
        NarrativeSection: {
            /** Expected */
            expected: number;
            /** Label */
            label: string;
            /** Moves */
            moves: components["schemas"]["NarrativeMove"][];
            /** Present */
            present: number;
            /** Section */
            section: string;
            /** Sentences */
            sentences: number;
            /** Words */
            words: number;
        };
        /** ProfileChoice */
        ProfileChoice: {
            id: components["schemas"]["DocumentType"];
            /** Label */
            label: string;
            /** Summary */
            summary: string;
        };
        /**
         * ProfileInfo
         * @description The article-type profile a check ran under.
         */
        ProfileInfo: {
            /**
             * Evidence
             * @description For a guessed type: the headings the guess rested on.
             * @default
             */
            evidence: string;
            /**
             * Guessed
             * @description True when the type was `auto` and guessed from the headings.
             */
            guessed: boolean;
            id: components["schemas"]["DocumentType"];
            /** Label */
            label: string;
            /**
             * Note
             * @description One line saying what the profile switched off, empty when nothing.
             * @default
             */
            note: string;
            /**
             * Rules Off
             * @description Rules not run for this type.
             */
            rules_off?: string[];
        };
        /** ReviewQuestion */
        ReviewQuestion: {
            /**
             * Evidence
             * @description Sentences of the document the verdict rests on (never logged).
             */
            evidence?: string[];
            /**
             * Id
             * @description A to E.
             */
            id: string;
            /** Points */
            points?: string[];
            /** Question */
            question: string;
            /**
             * Status
             * @description What the verdict rests on: detected (with evidence), not detected (the signals found nothing, which is not proof of absence), not assessed (the check was off) or not applicable (that part of the document is not there).
             * @default detected
             * @enum {string}
             */
            status: "yours" | "detected" | "not_detected" | "not_assessed" | "not_applicable";
            /**
             * Verdict
             * @description One line answering the question from the evidence.
             */
            verdict: string;
        };
        /**
         * ReviewReport
         * @description The critical reader's brief: five questions answered from the same
         *     deterministic analysis as the suggestions.
         */
        ReviewReport: {
            /**
             * Disclaimer
             * @description What the brief cannot do: it does not establish scientific validity.
             * @default
             */
            disclaimer: string;
            /** Questions */
            questions: components["schemas"]["ReviewQuestion"][];
            /** Sections */
            sections: string[];
            /** Source */
            source: string;
            /** Top Rules */
            top_rules?: components["schemas"]["ReviewRuleCount"][];
            /** Words */
            words: number;
        };
        /** ReviewRuleCount */
        ReviewRuleCount: {
            /** Count */
            count: number;
            /** Id */
            id: string;
            /** Short */
            short: string;
        };
        /** RuleInfo */
        RuleInfo: {
            category: components["schemas"]["Category"];
            fix_safety: components["schemas"]["FixSafety"];
            /** Id */
            id: string;
            /** Learn Ref */
            learn_ref?: string | null;
            /** Name */
            name: string;
            /**
             * Plain
             * @default
             */
            plain: string;
            /**
             * @description Draft mode shows sentence-level rules only.
             * @default sentence
             */
            scope: components["schemas"]["Scope"];
            /** Sections Excluded */
            sections_excluded?: string[] | null;
            /** Sections Only */
            sections_only?: string[] | null;
            /** Short */
            short: string;
            /** Source */
            source: string;
            /** Tier */
            tier: string;
            /** Why */
            why: string;
        };
        /** RulesResponse */
        RulesResponse: {
            /**
             * Checklists
             * @description Reporting checklists a caller can check against (S4).
             */
            checklists?: components["schemas"]["ChecklistChoiceInfo"][];
            /**
             * Profiles
             * @description Article types a caller can check as, in display order (S4).
             */
            profiles?: components["schemas"]["ProfileChoice"][];
            /** Rules */
            rules: components["schemas"]["RuleInfo"][];
        };
        /**
         * Scope
         * @description What a rule needs to judge: the sentence, or the whole document
         *     (figure citations, abbreviations defined once). Draft hides `document`.
         * @enum {string}
         */
        Scope: "sentence" | "document";
        /**
         * Segment
         * @description A stretch of `document.text` that came from one source file.
         *     `text[start:end]` equals that file's `[source_start : source_start + (end - start)]`.
         */
        Segment: {
            /** End */
            end: number;
            /**
             * Path
             * @description Path inside the upload, e.g. sections/methods.tex.
             */
            path: string;
            /**
             * Source Start
             * @description Offset in the source file, in code points.
             */
            source_start: number;
            /** Start */
            start: number;
        };
        /**
         * SourceFormat
         * @description How an uploaded file was read.
         * @enum {string}
         */
        SourceFormat: "latex" | "docx" | "markdown" | "plain";
        /** SourceInfo */
        SourceInfo: {
            /**
             * Filename
             * @description Echoed back to the caller; never logged.
             */
            filename: string;
            format: components["schemas"]["SourceFormat"];
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Structure */
            structure?: components["schemas"]["StructureItem"][];
            /**
             * Text
             * @description The text suggestions' spans index into: the source itself for .tex/.md/.txt, the expanded project for a .zip, the extracted paragraphs for .docx.
             */
            text: string;
            /**
             * Warnings
             * @description Things skipped or approximated while reading the file; never document text.
             */
            warnings?: string[];
        };
        /** Span */
        Span: {
            /**
             * Col
             * @description 1-based column of `start`; 0 if unknown.
             */
            col: number;
            /**
             * End
             * @description Offset into `content` in Unicode code points, exclusive.
             */
            end: number;
            /**
             * Line
             * @description 1-based line of `start`; 0 if unknown.
             */
            line: number;
            /**
             * Start
             * @description Offset into `content` in Unicode code points (Python str indices, NOT UTF-16 units), inclusive.
             */
            start: number;
        };
        /**
         * StructureItem
         * @description A figure, table, equation, caption or citation found in the source.
         *     Kept as structure for the consistency and cross-reference checks (S2b).
         */
        StructureItem: {
            /** End */
            end: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "figure" | "table" | "equation" | "caption" | "citation";
            /**
             * Label
             * @description \label key or Word bookmark, if any.
             */
            label?: string | null;
            /** Start */
            start: number;
        };
        /** Suggestion */
        Suggestion: {
            category: components["schemas"]["Category"];
            /** Confidence */
            confidence: number;
            fix_safety: components["schemas"]["FixSafety"];
            /**
             * Id
             * @description Stable fingerprint of (rule_id, start, end, text); used by /v1/feedback in S2.
             */
            id: string;
            /**
             * Learn Ref
             * @description Lesson id; Learn cards arrive in S4.
             */
            learn_ref?: string | null;
            /**
             * Message
             * @description One-line rationale, always shown.
             */
            message: string;
            /**
             * Plain
             * @description The explanation in everyday words, shown first; `why` is the fuller account.
             * @default
             */
            plain: string;
            /**
             * Replacement
             * @description A concrete fix, only from deterministic rules or a ≤40-char learned edit. Never generated prose.
             */
            replacement?: string | null;
            /** Rule Id */
            rule_id: string;
            /** Rule Name */
            rule_name: string;
            /**
             * Section
             * @description Detected section, e.g. methods, discussion, unknown.
             */
            section: string;
            /**
             * Source
             * @description Named provenance of the advice (CLAUDE.md #6).
             */
            source: string;
            span: components["schemas"]["Span"];
            /**
             * Text
             * @description The flagged source text, content[start:end].
             */
            text: string;
            /**
             * Tier
             * @description spelling | grammar | gec | craft | lens — which engine produced it.
             */
            tier: string;
            /**
             * Why
             * @description The teachable explanation.
             */
            why: string;
        };
        /** TierHealth */
        TierHealth: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Label */
            label: string;
            /**
             * Ok
             * @description Is this tier contributing suggestions right now?
             */
            ok: boolean;
            /**
             * Remedy
             * @default
             */
            remedy: string;
            /**
             * State
             * @description ready | missing | disabled | error | unstarted
             */
            state: string;
            /**
             * Tier
             * @description parser | spelling | grammar | gec | files | account (files: the LaTeX/.docx readers, shown only when one is missing; account: whether a signed-in caller's settings could be loaded)
             */
            tier: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WordLocation
         * @description How the add-in finds a suggestion in Word, which has no offsets:
         *     search `paragraph` for `snippet` and take match number `occurrence`.
         */
        WordLocation: {
            /** End */
            end: number;
            /**
             * Exact
             * @description False when the span is too long or unsafe to search for whole; `snippet` is then a prefix.
             */
            exact: boolean;
            /**
             * Occurrence
             * @description 0-based match number within the paragraph.
             */
            occurrence: number;
            /**
             * Paragraph
             * @description Index into the request's paragraphs.
             */
            paragraph: number;
            /**
             * Snippet
             * @description The text to search for.
             */
            snippet: string;
            /**
             * Start
             * @description Offset in that paragraph's text (code points).
             */
            start: number;
        };
        /**
         * WordParagraph
         * @description One paragraph as Office JS reports it (`body.paragraphs`).
         */
        WordParagraph: {
            /**
             * Kind
             * @description table: a table cell's paragraph (not prose).
             * @default body
             * @enum {string}
             */
            kind: "body" | "table";
            /**
             * Style
             * @description Word style name, e.g. "Heading 1", "Caption", "Normal".
             * @default
             */
            style: string;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** WordSuggestion */
        WordSuggestion: {
            category: components["schemas"]["Category"];
            /** Confidence */
            confidence: number;
            fix_safety: components["schemas"]["FixSafety"];
            /**
             * Id
             * @description Stable fingerprint of (rule_id, start, end, text); used by /v1/feedback in S2.
             */
            id: string;
            /**
             * Learn Ref
             * @description Lesson id; Learn cards arrive in S4.
             */
            learn_ref?: string | null;
            location: components["schemas"]["WordLocation"];
            /**
             * Message
             * @description One-line rationale, always shown.
             */
            message: string;
            /**
             * Plain
             * @description The explanation in everyday words, shown first; `why` is the fuller account.
             * @default
             */
            plain: string;
            /**
             * Replacement
             * @description A concrete fix, only from deterministic rules or a ≤40-char learned edit. Never generated prose.
             */
            replacement?: string | null;
            /** Rule Id */
            rule_id: string;
            /** Rule Name */
            rule_name: string;
            /**
             * Section
             * @description Detected section, e.g. methods, discussion, unknown.
             */
            section: string;
            /**
             * Source
             * @description Named provenance of the advice (CLAUDE.md #6).
             */
            source: string;
            span: components["schemas"]["Span"];
            /**
             * Text
             * @description The flagged source text, content[start:end].
             */
            text: string;
            /**
             * Tier
             * @description spelling | grammar | gec | craft | lens — which engine produced it.
             */
            tier: string;
            /**
             * Why
             * @description The teachable explanation.
             */
            why: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze: {
        parameters: {
            query?: never;
            header?: {
                /** @description `Bearer <Supabase access token>` when signed in. Omit for anonymous use. */
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sign-in invalid or expired (unauthorized), or this needs an account (sign_in_required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Document too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request failed validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Engine error (no document text in the body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sign-in could not be checked (auth_unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyzeFile: {
        parameters: {
            query?: never;
            header: {
                /** @description The file's name, percent-encoded (encodeURIComponent). Only its extension is used; it is never logged. */
                "x-researchly-filename": string;
                /** @description Optional JSON AnalyzeOptions. */
                "x-researchly-options"?: string | null;
                /** @description `Bearer <Supabase access token>` when signed in. Omit for anonymous use. */
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        /** @description The file's bytes. */
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeFileResponse"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sign-in invalid or expired (unauthorized), or this needs an account (sign_in_required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Document too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a supported file type (unsupported_file) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request failed validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Engine error (no document text in the body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sign-in could not be checked (auth_unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyzeWord: {
        parameters: {
            query?: never;
            header?: {
                /** @description `Bearer <Supabase access token>` when signed in. Omit for anonymous use. */
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeWordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeWordResponse"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sign-in invalid or expired (unauthorized), or this needs an account (sign_in_required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Document too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request failed validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Engine error (no document text in the body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sign-in could not be checked (auth_unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listLearn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnResponse"];
                };
            };
        };
    };
    getLearnCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnCard"];
                };
            };
            /** @description No such card */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesResponse"];
                };
            };
        };
    };
}
